spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zyn44321
  security:
      user:
        name: admin    # 自定义用户名
        password: 123  # 自定义密码
server:
    port: 28080
